# Generated by Django 5.0.1 on 2026-05-13 23:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0004_patient_patient_code'),
        ('records', '0005_file_auto_classified_file_classification_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_name', models.CharField(max_length=255)),
                ('dosage', models.CharField(blank=True, max_length=100)),
                ('frequency', models.CharField(blank=True, max_length=100)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(help_text='The deadline for this medication')),
                ('scheduled_times', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_reminders', to='patients.patient')),
                ('prescription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='records.prescription')),
            ],
            options={
                'db_table': 'medication_reminders',
                'indexes': [models.Index(fields=['patient', 'is_active'], name='medication__patient_e9973d_idx'), models.Index(fields=['end_date'], name='medication__end_dat_3d44ed_idx')],
            },
        ),
    ]
