# Generated by Django 5.0.1 on 2026-05-09 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications', models.BooleanField(default=True)),
                ('push_notifications', models.BooleanField(default=True)),
                ('sms_notifications', models.BooleanField(default=False)),
                ('appointment_reminders', models.BooleanField(default=True)),
                ('medication_reminders', models.BooleanField(default=True)),
                ('health_alerts', models.BooleanField(default=True)),
                ('newsletters', models.BooleanField(default=False)),
                ('profile_visibility', models.CharField(default='private', max_length=20)),
                ('share_data_research', models.BooleanField(default=False)),
                ('allow_ai_analysis', models.BooleanField(default=True)),
                ('data_sync_enabled', models.BooleanField(default=True)),
                ('theme', models.CharField(default='system', max_length=20)),
                ('language', models.CharField(default='en-US', max_length=20)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_settings',
            },
        ),
    ]
