# Generated by Django 5.0.1 on 2025-10-28 20:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AISummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_ids', models.JSONField(default=list)),
                ('text', models.TextField()),
                ('method', models.CharField(choices=[('textrank', 'TextRank Extractive'), ('other', 'Other')], default='textrank', max_length=20)),
                ('citations', models.JSONField(default=list)),
                ('ts', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'ai_summaries',
            },
        ),
        migrations.CreateModel(
            name='EmbeddingMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_type', models.CharField(max_length=50)),
                ('owner_id', models.IntegerField()),
                ('vector_dim', models.IntegerField(default=384)),
                ('meta', models.JSONField(default=dict)),
                ('ts', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'embeddings_meta',
            },
        ),
    ]
