# Generated by Django 5.0.1 on 2025-10-28 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aisummary',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_summaries', to='patients.patient'),
        ),
        migrations.AddIndex(
            model_name='embeddingmeta',
            index=models.Index(fields=['owner_type', 'owner_id'], name='embeddings__owner_t_0ab6f3_idx'),
        ),
        migrations.AddIndex(
            model_name='aisummary',
            index=models.Index(fields=['patient', 'ts'], name='ai_summarie_patient_0ea900_idx'),
        ),
    ]
