# Generated by Django 5.0.1 on 2026-02-07 15:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_initial'),
        ('patients', '0003_patient_address_patient_created_at_patient_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthSummaryShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_token', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_summary_shares', to='patients.patient')),
            ],
            options={
                'db_table': 'health_summary_shares',
                'indexes': [models.Index(fields=['share_token'], name='health_summ_share_t_8ad8f7_idx'), models.Index(fields=['patient', 'is_active'], name='health_summ_patient_52fada_idx')],
            },
        ),
    ]
