# Generated by Django 5.0.1 on 2026-05-10 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_add_health_summary_share_model'),
        ('patients', '0004_patient_patient_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='aisummary',
            name='is_saved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aisummary',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddIndex(
            model_name='aisummary',
            index=models.Index(fields=['patient', 'is_saved'], name='ai_summarie_patient_37401a_idx'),
        ),
    ]
