# Generated by Django 5.0.1 on 2026-05-21 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0004_aisummary_is_saved_aisummary_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReinforcedKnowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom', models.CharField(db_index=True, max_length=100)),
                ('disease', models.CharField(db_index=True, max_length=100)),
                ('weight', models.FloatField(default=1.0)),
                ('occurrences', models.IntegerField(default=1)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ai_reinforced_knowledge',
                'indexes': [models.Index(fields=['symptom', 'weight'], name='ai_reinforc_symptom_e1c555_idx'), models.Index(fields=['disease'], name='ai_reinforc_disease_33fa17_idx')],
                'unique_together': {('symptom', 'disease')},
            },
        ),
    ]
