# Generated by Django 5.0.1 on 2025-10-28 20:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_cents', models.IntegerField()),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('paid', 'Paid'), ('void', 'Void')], default='draft', max_length=10)),
                ('external_ref', models.CharField(blank=True, max_length=100, null=True)),
                ('ts', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'invoices',
            },
        ),
    ]
