# Generated by Django 5.0.1 on 2025-10-31 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('hold', 'Hold'), ('cancelled', 'Cancelled'), ('complete', 'Complete')], default='pending', max_length=10),
        ),
    ]
