# Generated by Django 5.0.1 on 2026-04-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_patient_address_patient_created_at_patient_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patient_code',
            field=models.CharField(db_index=True, default='', editable=False, max_length=16, unique=True),
            preserve_default=False,
        ),
    ]
