# Generated by Django 5.0.1 on 2026-05-17 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_providers', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='providerservice',
            new_name='provider_se_categor_a8f422_idx',
            old_name='provider_se_category_3e83d1_idx',
        ),
        migrations.RenameIndex(
            model_name='providerservice',
            new_name='provider_se_price_ec138c_idx',
            old_name='provider_se_price_b6c1f2_idx',
        ),
    ]
