# Generated by Django 5.0.1 on 2026-05-18 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_providers', '0002_rename_provider_se_category_3e83d1_idx_provider_se_categor_a8f422_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceproviderorganization',
            name='google_place_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='serviceproviderorganization',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='serviceproviderorganization',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='serviceproviderorganization',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
