# Generated by Django 5.0.1 on 2026-05-19 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_providers', '0003_serviceproviderorganization_google_place_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerservice',
            name='admin_feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='providerservice',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
