# Generated by Django 5.0.1 on 2026-05-19 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_patient_google_place_id_patient_latitude_and_more'),
        ('service_providers', '0004_providerservice_admin_feedback_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('slots_per_session', models.IntegerField(default=10, help_text='Maximum number of bookings for this time window')),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_availability', to='service_providers.serviceproviderorganization')),
                ('service', models.ForeignKey(blank=True, help_text='If null, apply to all services of this org', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='service_providers.providerservice')),
            ],
            options={
                'db_table': 'service_availability',
                'unique_together': {('organization', 'service', 'date', 'start_time')},
            },
        ),
        migrations.CreateModel(
            name='ServiceBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('preferred_time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('canceled', 'Canceled'), ('no_show', 'No Show')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('availability', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='service_providers.serviceavailability')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_bookings', to='patients.patient')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='service_providers.providerservice')),
            ],
            options={
                'db_table': 'service_bookings',
                'ordering': ['-date', '-preferred_time'],
            },
        ),
    ]
