# Generated by Django 5.0.1 on 2025-10-28 20:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('lab', 'Lab Result'), ('prescription', 'Prescription'), ('encounter', 'Encounter Note'), ('other', 'Other')], default='other', max_length=20)),
                ('filename', models.CharField(max_length=255)),
                ('storage_path', models.CharField(max_length=500)),
                ('mime', models.CharField(max_length=100)),
                ('size', models.IntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='patients.patient')),
            ],
            options={
                'db_table': 'files',
            },
        ),
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField(blank=True)),
                ('data', models.JSONField(default=dict)),
                ('ts', models.DateTimeField(default=django.utils.timezone.now)),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_results', to='records.file')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_results', to='patients.patient')),
            ],
            options={
                'db_table': 'lab_results',
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.JSONField(default=list)),
                ('notes', models.TextField(blank=True)),
                ('ts', models.DateTimeField(default=django.utils.timezone.now)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='doctors.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='patients.patient')),
            ],
            options={
                'db_table': 'prescriptions',
            },
        ),
        migrations.CreateModel(
            name='SymptomLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('cleaned_text', models.TextField(blank=True)),
                ('entities', models.JSONField(default=list)),
                ('ts', models.DateTimeField(default=django.utils.timezone.now)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptom_logs', to='patients.patient')),
            ],
            options={
                'db_table': 'symptom_logs',
            },
        ),
        migrations.CreateModel(
            name='Encounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField()),
                ('diagnosis', models.TextField(blank=True)),
                ('plan', models.TextField(blank=True)),
                ('ts', models.DateTimeField(default=django.utils.timezone.now)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encounters', to='doctors.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encounters', to='patients.patient')),
            ],
            options={
                'db_table': 'encounters',
                'indexes': [models.Index(fields=['patient', 'ts'], name='encounters_patient_7fdd5b_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['patient', 'kind'], name='files_patient_bb0d38_idx'),
        ),
        migrations.AddIndex(
            model_name='labresult',
            index=models.Index(fields=['patient', 'ts'], name='lab_results_patient_23a018_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['patient', 'ts'], name='prescriptio_patient_965fe0_idx'),
        ),
        migrations.AddIndex(
            model_name='symptomlog',
            index=models.Index(fields=['patient', 'ts'], name='symptom_log_patient_ab8608_idx'),
        ),
    ]
