# Generated by Django 5.0.1 on 2026-05-06 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_initial'),
        ('patients', '0004_patient_patient_code'),
        ('records', '0002_file_extracted_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('discontinued', 'Discontinued'), ('on_hold', 'On Hold')], default='active', max_length=20),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['patient', 'status'], name='prescriptio_patient_e097dd_idx'),
        ),
    ]
