# Generated by Django 5.0.1 on 2026-05-10 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_patient_patient_code'),
        ('records', '0003_prescription_expires_at_prescription_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='clinical_date',
            field=models.DateField(blank=True, help_text='The actual date from within the document', null=True),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['patient', 'clinical_date'], name='files_patient_cb403e_idx'),
        ),
    ]
