# Generated by Django 5.0.1 on 2026-05-13 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_file_clinical_date_file_files_patient_cb403e_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='auto_classified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='file',
            name='classification_note',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
