# Generated by Django 5.0.1 on 2026-05-17 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_patient_patient_code'),
        ('records', '0005_file_auto_classified_file_classification_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrescriptionFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocr_text', models.TextField(help_text='Raw OCR text chunk')),
                ('ai_extracted_json', models.JSONField(help_text='What ClinicalBERT extracted')),
                ('human_corrected_json', models.JSONField(help_text='Actual truth corrected by human')),
                ('reward_score', models.FloatField(default=0.0, help_text='Negative for error, positive for correct')),
                ('is_processed', models.BooleanField(default=False, help_text='Used in RL training loop')),
                ('ts', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
                ('prescription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='records.prescription')),
            ],
            options={
                'db_table': 'prescription_rl_feedback',
            },
        ),
    ]
