# Generated by Django 5.0.1 on 2026-05-09 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Notes from admin during approval process'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doctor',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='doctor',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
