# Generated by Django 5.0.1 on 2025-10-28 20:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.JSONField(default=dict)),
                ('expires_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked'), ('expired', 'Expired')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'consents',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_id', models.IntegerField()),
                ('actor_role', models.CharField(max_length=10)),
                ('action', models.CharField(max_length=50)),
                ('resource', models.CharField(max_length=100)),
                ('purpose', models.CharField(blank=True, max_length=200)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ts', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'audit_logs',
                'indexes': [models.Index(fields=['actor_id', 'ts'], name='audit_logs_actor_i_d238b3_idx'), models.Index(fields=['resource', 'ts'], name='audit_logs_resourc_1bf80c_idx')],
            },
        ),
    ]
