# Generated by Django 5.0.1 on 2025-10-28 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consent', '0002_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consent',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='patients.patient'),
        ),
        migrations.AddIndex(
            model_name='consent',
            index=models.Index(fields=['patient', 'doctor', 'status'], name='consents_patient_c2249a_idx'),
        ),
    ]
