# Generated by Django 5.0.1 on 2026-05-21 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consent', '0003_initial'),
        ('doctors', '0004_doctor_google_place_id_doctor_latitude_and_more'),
        ('patients', '0005_patient_google_place_id_patient_latitude_and_more'),
        ('service_providers', '0005_serviceavailability_servicebooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='consent',
            name='service_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='service_providers.serviceproviderorganization'),
        ),
        migrations.AlterField(
            model_name='consent',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='doctors.doctor'),
        ),
        migrations.AddIndex(
            model_name='consent',
            index=models.Index(fields=['patient', 'service_provider', 'status'], name='consents_patient_282c55_idx'),
        ),
    ]
