# Generated by Django 5.0.1 on 2026-02-08 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consent', '0003_initial'),
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='consent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='consent.consent'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='consent_granted',
            field=models.BooleanField(default=False),
        ),
    ]
