# Generated by Django 5.0.1 on 2026-05-04 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consent', '0003_initial'),
        ('doctors', '0002_initial'),
        ('patients', '0004_patient_patient_code'),
        ('scheduling', '0004_availability_session_fields'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'scheduled')), fields=('doctor', 'date', 'start_time'), name='unique_scheduled_appointment'),
        ),
    ]
